"""Replay logged EMG trials through candidate intent algorithms and plot them.

Four stacked panels on one time axis:
  1. chA raw
  2. chB analog envelope
  3. intent AS RECORDED  (what the firmware actually did during that trial)
  4. NEW INTENT          (what the selected algorithm would have done)

so a new detection method can be eyeballed against the real one on real data,
with no hardware and no reflashing.

    python tools/replay_intent.py data/emg_2026-07-23_193836.csv
    python tools/replay_intent.py data/emg_2026-07-23_193836.csv --algo adaptive
    python tools/replay_intent.py "data/emg_2026-07-23_*.csv" --algo cusum
    python tools/replay_intent.py --all --algo cusum        # every 7-23 trial
    python tools/replay_intent.py --list

ADDING AN ALGORITHM  (the only supported way — do not edit this file)
Drop one file in tools/algos/, e.g. tools/algos/mything.py:

    NAME = "mything"
    DOC  = "one line, shows up in --list and on the plot"

    class Detector:
        '''STRICTLY CAUSAL: update() is fed one sample at a time, in order,
        and never sees the future. No file-wide percentiles, no two passes.'''
        def __init__(self, fs=500):
            ...
        def update(self, chB, chA):
            # returns (activity, t_on, t_off, t_full) for THIS sample.
            # thresholds may move over time; they just cannot come from
            # data that has not arrived yet.
            return act, t_on, t_off, t_full

The latching state machine below is shared by every algorithm, so only the
front-end differs and comparisons stay apples-to-apples.
"""
import argparse
import csv
import glob
import importlib.util
import os
import sys

SAMPLE_HZ, TICK_DIV = 500, 10
TICK_S = TICK_DIV / SAMPLE_HZ

# shared FSM timings (match the firmware)
DEBOUNCE_MS, RELAX_MS = 80, 150
OPEN_DWELL_MS, OPEN_DRIVE_MS = 2000, 2500
OPEN_SPEED, CLOSE_MIN = 600, 250
DEAD_COUNTS = 300           # chB below this = front-end unpowered, force OPEN
ST_OPEN, ST_CLOSING, ST_HOLDING, ST_OPENING = range(4)
NAMES = ["OPEN", "CLOSING", "HOLDING", "OPENING"]


def pct(v, q):
    s = sorted(v); k = (len(s) - 1) * q / 100.0
    lo = int(k); hi = min(lo + 1, len(s) - 1)
    return s[lo] + (s[hi] - s[lo]) * (k - lo)


# ------------------------------------------------- legacy (NON-CAUSAL) algos
# Kept only as the incumbent reference to beat. They compute thresholds from
# file-wide percentiles, i.e. they peek at the future — a real device cannot.
def algo_simple(chB, chA, src):
    """[non-causal] Fixed thresholds above a once-tared floor."""
    sig = chB if src == "chB" else chA
    live = [x for x in sig if x > 300] or sig
    floor = pct(live, 10)
    out, s = [], 0.0
    for x in sig:
        a = max(0.0, x - floor) if src == "chB" else abs(x - floor)
        s += 0.04 * (a - s)                      # ~50 ms de-jitter
        out.append(s)
    return out, 750, 350, 1750


def algo_adaptive(chB, chA, src):
    """[non-causal] Tracking baseline + thresholds from the envelope spread."""
    sig = chB if src == "chB" else chA
    base = float(sig[0]); env = 0.0; out = []
    for x in sig:
        base += (0.02 if x < base else 0.0002) * (x - base)
        r = max(0.0, x - base) if src == "chB" else abs(x - base)
        env += 0.01 * (r - env)
        out.append(env)
    rest, mvc = pct(out, 20), pct(out, 99)
    span = mvc - rest
    return out, rest + 0.28 * span, rest + 0.12 * span, rest + 0.80 * span


def algo_fixed(chB, chA, src):
    """[non-causal] The original: one-shot mean tare, rectify, 200 ms EMA."""
    sig = chB if src == "chB" else chA
    base = sum(sig[:250]) / min(250, len(sig))
    env = 0.0; out = []
    for x in sig:
        env += 0.01 * (abs(x - base) - env)
        out.append(env)
    rest, mvc = pct(out, 20), pct(out, 99)
    span = mvc - rest
    return out, rest + 0.28 * span, rest + 0.12 * span, rest + 0.80 * span


ALGOS = {
    "simple":   (algo_simple,   "[non-causal] fixed thresholds over a tared floor"),
    "adaptive": (algo_adaptive, "[non-causal] tracking baseline + spread thresholds"),
    "fixed":    (algo_fixed,    "[non-causal] one-shot tare + heavy EMA (original)"),
}


# ------------------------------------------------------------ plugin loading
def _wrap(mod):
    """Drive a streaming Detector one sample at a time — no lookahead possible."""
    def run(chB, chA, src):
        det = mod.Detector(SAMPLE_HZ)
        act, on, off, full = [], [], [], []
        for b, a in zip(chB, chA):
            v, o, f, u = det.update(b, a)
            act.append(v); on.append(o); off.append(f); full.append(u)
        return act, on, off, full
    run.module = mod        # lets play_replay.py build its own live Detector
    return run


def load_plugins():
    d = os.path.join(os.path.dirname(os.path.abspath(__file__)), "algos")
    for path in sorted(glob.glob(os.path.join(d, "*.py"))):
        if os.path.basename(path).startswith("_"):
            continue
        spec = importlib.util.spec_from_file_location(
            "algos_" + os.path.basename(path)[:-3], path)
        mod = importlib.util.module_from_spec(spec)
        try:
            spec.loader.exec_module(mod)
            ALGOS[mod.NAME] = (_wrap(mod), mod.DOC)
        except Exception as e:                       # a broken plugin is not fatal
            print(f"! skipping {os.path.basename(path)}: {e}", file=sys.stderr)


# ---------------------------------------------------------------- shared FSM
def _at(th, i):
    return th[i] if isinstance(th, list) else th


class Machine:
    """The shared latching FSM, one tick at a time.

    Batch replay and the live player both drive this, so they cannot drift
    apart. One tick = TICK_DIV samples, matching the firmware's control rate.
    """

    def __init__(self):
        self.st = ST_OPEN
        self.ah = self.bo = 0.0
        self.open_t = 0.0
        self.intent = 0

    def step(self, e, on, off, full, now_ms, dead=False):
        """Advance one control tick; returns (intent, state)."""
        intent = 0
        if dead:                      # front-end unpowered: safe state, no latch
            self.st = ST_OPEN
            self.ah = self.bo = 0.0
            self.intent = 0
            return 0, self.st
        self.ah = self.ah + TICK_S * 1000 if e > on else 0
        self.bo = self.bo + TICK_S * 1000 if e < off else 0
        if self.st == ST_OPEN:
            if self.ah >= DEBOUNCE_MS: self.st = ST_CLOSING
        elif self.st == ST_CLOSING:
            frac = max(0.0, min(1.0, (e - on) / max(1e-9, full - on)))
            intent = CLOSE_MIN + int(frac * (1000 - CLOSE_MIN))
            if self.bo >= RELAX_MS: self.st = ST_HOLDING
        elif self.st == ST_HOLDING:
            if self.ah >= DEBOUNCE_MS: self.st = ST_CLOSING
            elif self.bo >= OPEN_DWELL_MS:
                self.st = ST_OPENING; self.open_t = now_ms
        elif self.st == ST_OPENING:
            intent = -OPEN_SPEED
            if self.ah >= DEBOUNCE_MS: self.st = ST_CLOSING
            elif now_ms - self.open_t >= OPEN_DRIVE_MS: self.st = ST_OPEN
        self.intent = intent
        return intent, self.st


def run_fsm(act, t_on, t_off, t_full, raw=None):
    """Batch wrapper over Machine.

    Thresholds may be scalars or per-sample lists (streaming detectors move
    them as they learn). `raw` is chB; below DEAD_COUNTS the front-end is
    unpowered and the hand is forced OPEN — a safety floor every algo inherits
    rather than reimplements.
    """
    m = Machine()
    intents, states = [], []
    for i in range(0, len(act), TICK_DIV):
        dead = raw is not None and raw[i] < DEAD_COUNTS
        intent, st = m.step(act[i], _at(t_on, i), _at(t_off, i), _at(t_full, i),
                            i / SAMPLE_HZ * 1000, dead)
        intents.append(intent); states.append(st)
    return intents, states


def score(states, intents, recorded, raw):
    """Label-free metrics. No ground truth exists, so these are proxies."""
    n = len(states)
    frac = {s: states.count(s) / n * 100 for s in range(4)}
    trans = sum(1 for i in range(1, n) if states[i] != states[i - 1])
    per_min = trans / (n * TICK_S / 60.0)
    # false activity: non-OPEN while the front-end was dead (chB pinned at 0)
    dead = [i for i in range(n) if raw[i * TICK_DIV] < DEAD_COUNTS]
    ghost = (sum(1 for i in dead if states[i] != ST_OPEN) / len(dead) * 100) if dead else 0.0
    agree = None
    if recorded:
        m = min(n, len(recorded) // TICK_DIV)
        sgn = lambda v: (v > 0) - (v < 0)
        agree = sum(1 for i in range(m)
                    if sgn(intents[i]) == sgn(recorded[i * TICK_DIV])) / m * 100
    return frac, per_min, ghost, agree


def load(path):
    T, A, B, I = [], [], [], []
    for row in list(csv.reader(open(path)))[1:]:
        if len(row) < 3:
            continue
        try:
            T.append(float(row[0])); A.append(int(row[1])); B.append(int(row[2]))
            I.append(int(row[4]) if len(row) >= 5 else None)
        except (ValueError, IndexError):
            pass
    t0 = T[0]
    return [t - t0 for t in T], A, B, I


def plot(path, T, A, B, recorded, results, src, root):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    SURF, INK, INK2, MUTE = "#fcfcfb", "#0b0b0b", "#52514e", "#898781"
    GRID, BASE, BLUE, ORANGE = "#e1e0d9", "#c3c2b7", "#2a78d6", "#eb6834"
    name = os.path.basename(path)

    rows = 3 + len(results)
    fig, axes = plt.subplots(rows, 1, figsize=(12, 2.0 * rows), sharex=True)
    fig.patch.set_facecolor(SURF)
    for ax in axes:
        ax.set_facecolor(SURF); ax.grid(True, color=GRID, linewidth=0.8)
        for s in ax.spines.values(): s.set_color(BASE)
        ax.tick_params(colors=MUTE, labelsize=8)

    axes[0].plot(T, A, color=MUTE, linewidth=0.6)
    axes[0].set_ylabel("chA raw", color=INK2, fontsize=8)
    axes[0].set_title(f"{name}  —  recorded vs new intent  (source: {src})",
                      color=INK, fontsize=12, loc="left")
    axes[1].plot(T, B, color=BLUE, linewidth=0.6)
    axes[1].set_ylabel("chB env", color=INK2, fontsize=8)

    def intent_panel(ax, t, y, label, color):
        ax.axhline(0, color=BASE, linewidth=0.9)
        ax.plot(t, y, color=color, linewidth=1.1)
        ax.fill_between(t, y, 0, color=color, alpha=0.12)
        ax.set_ylim(-1100, 1100); ax.set_yticks([-1000, 0, 1000])
        ax.set_ylabel(label, color=INK2, fontsize=8)

    if recorded:
        intent_panel(axes[2], T[:len(recorded)], recorded, "intent\n(recorded)", MUTE)
    else:
        axes[2].text(0.5, 0.5, "no intent column in this CSV (pre-4-field firmware)",
                     transform=axes[2].transAxes, ha="center", color=MUTE, fontsize=9)
        axes[2].set_ylabel("intent\n(recorded)", color=INK2, fontsize=8)

    tt = [i * TICK_S for i in range(len(results[0][2]))]
    for ax, (n, act, intents, stats) in zip(axes[3:], results):
        intent_panel(ax, tt, intents, f"NEW intent\n({n})", ORANGE)
        ax.text(0.008, 0.90, f"{n}  —  {ALGOS[n][1]}", transform=ax.transAxes,
                color=INK, fontsize=8.5, va="top",
                bbox=dict(boxstyle="round,pad=0.25", fc=SURF, ec=GRID, lw=0.8))
    axes[-1].set_xlabel("time (s)", color=INK2, fontsize=8)

    outdir = os.path.join(root, "output", "replay")
    os.makedirs(outdir, exist_ok=True)
    algos = "-".join(n for n, _, _, _ in results)
    out = os.path.join(outdir, name.replace(".csv", f"_{algos}.png"))
    fig.savefig(out, dpi=130, facecolor=SURF, bbox_inches="tight")
    plt.close(fig)
    return os.path.relpath(out, root)


def main():
    load_plugins()
    ap = argparse.ArgumentParser()
    ap.add_argument("file", nargs="?", help="CSV path or glob (quote the glob)")
    ap.add_argument("--algo", default="simple",
                    help="comma-separated; one 'new intent' panel each")
    ap.add_argument("--src", default="chB", choices=["chB", "chA"])
    ap.add_argument("--all", action="store_true", help="every 7-23 trial in data/")
    ap.add_argument("--no-plot", action="store_true", help="metrics only, faster")
    ap.add_argument("--list", action="store_true", help="show available algorithms")
    args = ap.parse_args()

    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    if args.list or not (args.file or args.all):
        print("algorithms:")
        for k, (_, doc) in ALGOS.items():
            print(f"  {k:12} {doc}")
        print("\nusage: python tools/replay_intent.py --all --algo <name>")
        return

    if args.all:
        files = sorted(glob.glob(os.path.join(root, "data", "emg_2026-07-23_*.csv")))
    else:
        files = sorted(glob.glob(args.file)) or [args.file]

    names = [a.strip() for a in args.algo.split(",") if a.strip()]
    for n in names:
        if n not in ALGOS:
            sys.exit(f"unknown algo '{n}'. available: {', '.join(ALGOS)}")

    print(f"{'trial':30} {'algo':12} {'OPEN':>5} {'CLOS':>5} {'HOLD':>5} "
          f"{'OPNG':>5} {'sw/min':>7} {'ghost%':>7} {'agree%':>7}")
    for path in files:
        T, A, B, I = load(path)
        if len(B) < SAMPLE_HZ:
            print(f"{os.path.basename(path):30} (too short, skipped)")
            continue
        recorded = [x for x in I if x is not None]
        results = []
        for n in names:
            act, t_on, t_off, t_full = ALGOS[n][0](B, A, args.src)
            intents, states = run_fsm(act, t_on, t_off, t_full, raw=B)
            frac, sw, ghost, agree = score(states, intents, recorded, B)
            print(f"{os.path.basename(path):30} {n:12} {frac[0]:5.0f} {frac[1]:5.0f} "
                  f"{frac[2]:5.0f} {frac[3]:5.0f} {sw:7.1f} {ghost:7.1f} "
                  f"{('%.0f' % agree) if agree is not None else '-':>7}")
            results.append((n, act, intents, (frac, sw, ghost, agree)))
        if not args.no_plot:
            plot(path, T, A, B, recorded, results, args.src, root)
    if not args.no_plot:
        print(f"\nplots in output/replay/")


if __name__ == "__main__":
    main()
